### PR TITLE
[#79] readinessProbe.sh-script fails

### LINKED ISSUE #79: readinessProbe.sh-script fails silently
**Describe the bug**
The problem is that when the scripts fetch an empty list from `/proc/net/tcp` and since it doesn't get an exception it won't fetch `/proc/net/tcp6` where the ports are really are. It then doesn't find any open ports.

The problem here is that the value-variable is not stripped before it is split. This results in all ports equals `None` and then it will always continue - no matter whether the ports are listening or not.

### PR DESCRIPTION
**Pull request by aboucham**
Fix the readinessProbe.sh-script issue.

### CODE REVIEW

File: modules/activemq-artemis-launch/added/readinessProbe.sh [hunk 1]
```diff
@@ -23,13 +23,16 @@ import socket
...
-  tcp_file = open("/proc/net/tcp6", "r")
-tcp_lines = tcp_file.readlines()
-header = tcp_lines.pop(0)
-tcp_file.close()
+tcp_lines = []
+for tcp_file_path in ["/proc/net/tcp", "/proc/net/tcp6"]:
+  try:
+    tcp_file = open(tcp_file_path, "r")
+    lines = tcp_file.readlines()
+    header = lines.pop(0)
```
Comment (gaohoward) [inline modules/activemq-artemis-launch/added/readinessProbe.sh]: if /proc/net/tcp is empty you will get empty list, `lines.pop(0)` would throw exception.
I think a check should be added here, something like
```
    if len(lines) > 0:
      header = lines.pop(0)
      tcp_lines.extend(lines)

```
